INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (11, 0,'Rondônia');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (12, 0,'Acre');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (13, 0,'Amazonas');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (14, 0,'Roraima');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (15, 0,'Pará');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (16, 0,'Amapá');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (17, 0,'Tocantins');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (21, 0,'Maranhão');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (22, 0,'Piauí');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (23, 0,'Ceará');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (24, 0,'Rio Grande do Norte');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (25, 0,'Paraíba');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (26, 0,'Pernambuco');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (27, 0,'Alagoas');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (28, 0,'Sergipe');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (29, 0,'Bahia');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (31, 0,'Minas Gerais');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (32, 0,'Espírito Santo');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (33, 0,'Rio de Janeiro');

INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (41, 0,'Paraná');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (42, 0,'Santa Catarina');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (43, 0,'Rio Grande do Sul');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (50, 0,'Mato Grosso do Sul');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (51, 0,'Mato Grosso');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (52, 0,'Goiás');
INSERT INTO uf (cod_uf, habilitado, nome_uf) VALUES (53, 0,'Distrito Federal');
